### ISSUE TITLE
indentNextLinePattern is empty

### ISSUE THREAD

**Issue by matthewbarr** [puppet-textmate-bundle/puppet-textmate-bundle#3]
- indentNextLinePattern is empty, should be deleted.

(Or actually used, i suppose. - @matthewbarr)

(From the Textmate Bundle maintainer.)

**Comment by matthewbarr** [comment]
@masterzen   -  I actually haven't looked at these patterns yet, so I don't know if we should be using them.  

Can you take a quick look, and decide if it's something that we should actually implement, or just delete?
(This is the last of the Textmate 1.X safe recommendations, I'll be getting a list of the 2.x only ones later, but we won't implement those in the main branch, especially not with you still on 1.5 :)

**Comment by masterzen** [comment]
I'll have look over the week-end, thanks!
